cp admin/admin_proxy.php ../../../admin/admin_proxy.php
cp templates/subSilver/admin/proxy_main_body.tpl ../../../templates/subSilver/admin/proxy_main_body.tpl
cp templates/subSilver/admin/proxy_test_body.tpl ../../../templates/subSilver/admin/proxy_test_body.tpl
cp templates/subSilver/admin/proxy_list_body.tpl ../../../templates/subSilver/admin/proxy_list_body.tpl
cp includes/functions_proxy.php ../../../includes/functions_proxy.php
cp proxy/connect.php ../../../proxy/connect.php
cp proxy/serve.php ../../../proxy/serve.php
cp proxy/index.htm ../../../proxy/index.htm
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
cp ../../../includes/usercp_register.php backups/includes/usercp_register.php.txt
cp processed/includes/usercp_register.php.txt ../../../includes/usercp_register.php
