copy admin\admin_proxy.php ..\..\..\admin\admin_proxy.php
copy templates\subSilver\admin\proxy_main_body.tpl ..\..\..\templates\subSilver\admin\proxy_main_body.tpl
copy templates\subSilver\admin\proxy_test_body.tpl ..\..\..\templates\subSilver\admin\proxy_test_body.tpl
copy templates\subSilver\admin\proxy_list_body.tpl ..\..\..\templates\subSilver\admin\proxy_list_body.tpl
copy includes\functions_proxy.php ..\..\..\includes\functions_proxy.php
copy proxy\connect.php ..\..\..\proxy\connect.php
copy proxy\serve.php ..\..\..\proxy\serve.php
copy proxy\index.htm ..\..\..\proxy\index.htm
copy ..\..\..\includes\constants.php backups\includes\constants.php.txt
copy processed\includes\constants.php.txt ..\..\..\includes\constants.php
copy ..\..\..\language\lang_english\lang_main.php backups\language\lang_english\lang_main.php.txt
copy processed\language\lang_english\lang_main.php.txt ..\..\..\language\lang_english\lang_main.php
copy ..\..\..\language\lang_english\lang_admin.php backups\language\lang_english\lang_admin.php.txt
copy processed\language\lang_english\lang_admin.php.txt ..\..\..\language\lang_english\lang_admin.php
copy ..\..\..\includes\usercp_register.php backups\includes\usercp_register.php.txt
copy processed\includes\usercp_register.php.txt ..\..\..\includes\usercp_register.php
