cp root/admin/admin_anti_spam_acp.php ../../../admin/admin_anti_spam_acp.php
cp root/admin/admin_anti_spam_acp_inactive.php ../../../admin/admin_anti_spam_acp_inactive.php
cp root/admin/admin_anti_spam_acp_log.php ../../../admin/admin_anti_spam_acp_log.php
cp root/admin/admin_anti_spam_acp_profile.php ../../../admin/admin_anti_spam_acp_profile.php
cp root/includes/better_captcha_fonts/13.ttf ../../../includes/better_captcha_fonts/13.ttf
cp root/includes/better_captcha_fonts/7.ttf ../../../includes/better_captcha_fonts/7.ttf
cp root/includes/better_captcha_fonts/4.ttf ../../../includes/better_captcha_fonts/4.ttf
cp root/includes/better_captcha_fonts/5.ttf ../../../includes/better_captcha_fonts/5.ttf
cp root/includes/better_captcha_fonts/.htaccess ../../../includes/better_captcha_fonts/.htaccess
cp root/includes/better_captcha_fonts/8.ttf ../../../includes/better_captcha_fonts/8.ttf
cp root/includes/better_captcha_fonts/11.ttf ../../../includes/better_captcha_fonts/11.ttf
cp root/includes/better_captcha_fonts/3.ttf ../../../includes/better_captcha_fonts/3.ttf
cp root/includes/better_captcha_fonts/1.ttf ../../../includes/better_captcha_fonts/1.ttf
cp root/includes/better_captcha_fonts/15.ttf ../../../includes/better_captcha_fonts/15.ttf
cp root/includes/better_captcha_fonts/14.ttf ../../../includes/better_captcha_fonts/14.ttf
cp root/includes/better_captcha_fonts/12.ttf ../../../includes/better_captcha_fonts/12.ttf
cp root/includes/better_captcha_fonts/2.ttf ../../../includes/better_captcha_fonts/2.ttf
cp root/includes/better_captcha_fonts/10.ttf ../../../includes/better_captcha_fonts/10.ttf
cp root/includes/better_captcha_fonts/9.ttf ../../../includes/better_captcha_fonts/9.ttf
cp root/includes/better_captcha_fonts/6.ttf ../../../includes/better_captcha_fonts/6.ttf
cp root/includes/anti_spam_acp.php ../../../includes/anti_spam_acp.php
cp root/includes/functions_anti_spam_acp.php ../../../includes/functions_anti_spam_acp.php
cp root/includes/usercp_captcha.php ../../../includes/usercp_captcha.php
cp root/language/lang_english/email/admin_spam_notification.tpl ../../../language/lang_english/email/admin_spam_notification.tpl
cp root/language/lang_english/lang_anti_spam_acp.php ../../../language/lang_english/lang_anti_spam_acp.php
cp root/templates/subSilver/admin/anti_spam_acp.tpl ../../../templates/subSilver/admin/anti_spam_acp.tpl
cp root/templates/subSilver/admin/anti_spam_acp_inactive.tpl ../../../templates/subSilver/admin/anti_spam_acp_inactive.tpl
cp root/templates/subSilver/admin/anti_spam_acp_log.tpl ../../../templates/subSilver/admin/anti_spam_acp_log.tpl
cp root/templates/subSilver/admin/anti_spam_acp_profile.tpl ../../../templates/subSilver/admin/anti_spam_acp_profile.tpl
cp root/templates/subSilver/images/arrowdown.png ../../../templates/subSilver/images/arrowdown.png
cp root/templates/subSilver/images/arrowright.png ../../../templates/subSilver/images/arrowright.png
cp ../../../admin/admin_users.php backups/admin/admin_users.php.txt
cp processed/admin/admin_users.php.txt ../../../admin/admin_users.php
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../includes/functions.php backups/includes/functions.php.txt
cp processed/includes/functions.php.txt ../../../includes/functions.php
cp ../../../includes/functions_post.php backups/includes/functions_post.php.txt
cp processed/includes/functions_post.php.txt ../../../includes/functions_post.php
cp ../../../includes/usercp_register.php backups/includes/usercp_register.php.txt
cp processed/includes/usercp_register.php.txt ../../../includes/usercp_register.php
cp ../../../templates/subSilver/admin/user_edit_body.tpl backups/templates/subSilver/admin/user_edit_body.tpl.txt
cp processed/templates/subSilver/admin/user_edit_body.tpl.txt ../../../templates/subSilver/admin/user_edit_body.tpl
cp ../../../templates/subSilver/overall_footer.tpl backups/templates/subSilver/overall_footer.tpl.txt
cp processed/templates/subSilver/overall_footer.tpl.txt ../../../templates/subSilver/overall_footer.tpl
cp ../../../templates/subSilver/posting_body.tpl backups/templates/subSilver/posting_body.tpl.txt
cp processed/templates/subSilver/posting_body.tpl.txt ../../../templates/subSilver/posting_body.tpl
cp ../../../templates/subSilver/profile_add_body.tpl backups/templates/subSilver/profile_add_body.tpl.txt
cp processed/templates/subSilver/profile_add_body.tpl.txt ../../../templates/subSilver/profile_add_body.tpl
cp ../../../memberlist.php backups/memberlist.php.txt
cp processed/memberlist.php.txt ../../../memberlist.php
cp ../../../posting.php backups/posting.php.txt
cp processed/posting.php.txt ../../../posting.php
cp ../../../profile.php backups/profile.php.txt
cp processed/profile.php.txt ../../../profile.php
