copy root\admin\admin_anti_spam_acp.php ..\..\..\admin\admin_anti_spam_acp.php
copy root\admin\admin_anti_spam_acp_inactive.php ..\..\..\admin\admin_anti_spam_acp_inactive.php
copy root\admin\admin_anti_spam_acp_log.php ..\..\..\admin\admin_anti_spam_acp_log.php
copy root\admin\admin_anti_spam_acp_profile.php ..\..\..\admin\admin_anti_spam_acp_profile.php
copy root\includes\better_captcha_fonts\13.ttf ..\..\..\includes\better_captcha_fonts\13.ttf
copy root\includes\better_captcha_fonts\7.ttf ..\..\..\includes\better_captcha_fonts\7.ttf
copy root\includes\better_captcha_fonts\4.ttf ..\..\..\includes\better_captcha_fonts\4.ttf
copy root\includes\better_captcha_fonts\5.ttf ..\..\..\includes\better_captcha_fonts\5.ttf
copy root\includes\better_captcha_fonts\.htaccess ..\..\..\includes\better_captcha_fonts\.htaccess
copy root\includes\better_captcha_fonts\8.ttf ..\..\..\includes\better_captcha_fonts\8.ttf
copy root\includes\better_captcha_fonts\11.ttf ..\..\..\includes\better_captcha_fonts\11.ttf
copy root\includes\better_captcha_fonts\3.ttf ..\..\..\includes\better_captcha_fonts\3.ttf
copy root\includes\better_captcha_fonts\1.ttf ..\..\..\includes\better_captcha_fonts\1.ttf
copy root\includes\better_captcha_fonts\15.ttf ..\..\..\includes\better_captcha_fonts\15.ttf
copy root\includes\better_captcha_fonts\14.ttf ..\..\..\includes\better_captcha_fonts\14.ttf
copy root\includes\better_captcha_fonts\12.ttf ..\..\..\includes\better_captcha_fonts\12.ttf
copy root\includes\better_captcha_fonts\2.ttf ..\..\..\includes\better_captcha_fonts\2.ttf
copy root\includes\better_captcha_fonts\10.ttf ..\..\..\includes\better_captcha_fonts\10.ttf
copy root\includes\better_captcha_fonts\9.ttf ..\..\..\includes\better_captcha_fonts\9.ttf
copy root\includes\better_captcha_fonts\6.ttf ..\..\..\includes\better_captcha_fonts\6.ttf
copy root\includes\anti_spam_acp.php ..\..\..\includes\anti_spam_acp.php
copy root\includes\functions_anti_spam_acp.php ..\..\..\includes\functions_anti_spam_acp.php
copy root\includes\usercp_captcha.php ..\..\..\includes\usercp_captcha.php
copy root\language\lang_english\email\admin_spam_notification.tpl ..\..\..\language\lang_english\email\admin_spam_notification.tpl
copy root\language\lang_english\lang_anti_spam_acp.php ..\..\..\language\lang_english\lang_anti_spam_acp.php
copy root\templates\subSilver\admin\anti_spam_acp.tpl ..\..\..\templates\subSilver\admin\anti_spam_acp.tpl
copy root\templates\subSilver\admin\anti_spam_acp_inactive.tpl ..\..\..\templates\subSilver\admin\anti_spam_acp_inactive.tpl
copy root\templates\subSilver\admin\anti_spam_acp_log.tpl ..\..\..\templates\subSilver\admin\anti_spam_acp_log.tpl
copy root\templates\subSilver\admin\anti_spam_acp_profile.tpl ..\..\..\templates\subSilver\admin\anti_spam_acp_profile.tpl
copy root\templates\subSilver\images\arrowdown.png ..\..\..\templates\subSilver\images\arrowdown.png
copy root\templates\subSilver\images\arrowright.png ..\..\..\templates\subSilver\images\arrowright.png
copy ..\..\..\admin\admin_users.php backups\admin\admin_users.php.txt
copy processed\admin\admin_users.php.txt ..\..\..\admin\admin_users.php
copy ..\..\..\includes\constants.php backups\includes\constants.php.txt
copy processed\includes\constants.php.txt ..\..\..\includes\constants.php
copy ..\..\..\includes\functions.php backups\includes\functions.php.txt
copy processed\includes\functions.php.txt ..\..\..\includes\functions.php
copy ..\..\..\includes\functions_post.php backups\includes\functions_post.php.txt
copy processed\includes\functions_post.php.txt ..\..\..\includes\functions_post.php
copy ..\..\..\includes\usercp_register.php backups\includes\usercp_register.php.txt
copy processed\includes\usercp_register.php.txt ..\..\..\includes\usercp_register.php
copy ..\..\..\templates\subSilver\admin\user_edit_body.tpl backups\templates\subSilver\admin\user_edit_body.tpl.txt
copy processed\templates\subSilver\admin\user_edit_body.tpl.txt ..\..\..\templates\subSilver\admin\user_edit_body.tpl
copy ..\..\..\templates\subSilver\overall_footer.tpl backups\templates\subSilver\overall_footer.tpl.txt
copy processed\templates\subSilver\overall_footer.tpl.txt ..\..\..\templates\subSilver\overall_footer.tpl
copy ..\..\..\templates\subSilver\posting_body.tpl backups\templates\subSilver\posting_body.tpl.txt
copy processed\templates\subSilver\posting_body.tpl.txt ..\..\..\templates\subSilver\posting_body.tpl
copy ..\..\..\templates\subSilver\profile_add_body.tpl backups\templates\subSilver\profile_add_body.tpl.txt
copy processed\templates\subSilver\profile_add_body.tpl.txt ..\..\..\templates\subSilver\profile_add_body.tpl
copy ..\..\..\memberlist.php backups\memberlist.php.txt
copy processed\memberlist.php.txt ..\..\..\memberlist.php
copy ..\..\..\posting.php backups\posting.php.txt
copy processed\posting.php.txt ..\..\..\posting.php
copy ..\..\..\profile.php backups\profile.php.txt
copy processed\profile.php.txt ..\..\..\profile.php
