cp viewtopic_quickreply.php ../../../includes/viewtopic_quickreply.php
cp viewtopic_quickreply.tpl ../../../templates/subSilver/viewtopic_quickreply.tpl
cp quickreply.gif ../../../templates/subSilver/images/lang_english/quickreply.gif
cp ../../../admin/admin_board.php backups/admin/admin_board.php.txt
cp processed/admin/admin_board.php.txt ../../../admin/admin_board.php
cp ../../../admin/admin_users.php backups/admin/admin_users.php.txt
cp processed/admin/admin_users.php.txt ../../../admin/admin_users.php
cp ../../../includes/functions_selects.php backups/includes/functions_selects.php.txt
cp processed/includes/functions_selects.php.txt ../../../includes/functions_selects.php
cp ../../../includes/usercp_avatar.php backups/includes/usercp_avatar.php.txt
cp processed/includes/usercp_avatar.php.txt ../../../includes/usercp_avatar.php
cp ../../../includes/usercp_register.php backups/includes/usercp_register.php.txt
cp processed/includes/usercp_register.php.txt ../../../includes/usercp_register.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../templates/subSilver/admin/board_config_body.tpl backups/templates/subSilver/admin/board_config_body.tpl.txt
cp processed/templates/subSilver/admin/board_config_body.tpl.txt ../../../templates/subSilver/admin/board_config_body.tpl
cp ../../../templates/subSilver/admin/user_edit_body.tpl backups/templates/subSilver/admin/user_edit_body.tpl.txt
cp processed/templates/subSilver/admin/user_edit_body.tpl.txt ../../../templates/subSilver/admin/user_edit_body.tpl
cp ../../../templates/subSilver/profile_add_body.tpl backups/templates/subSilver/profile_add_body.tpl.txt
cp processed/templates/subSilver/profile_add_body.tpl.txt ../../../templates/subSilver/profile_add_body.tpl
cp ../../../templates/subSilver/viewtopic_body.tpl backups/templates/subSilver/viewtopic_body.tpl.txt
cp processed/templates/subSilver/viewtopic_body.tpl.txt ../../../templates/subSilver/viewtopic_body.tpl
cp ../../../templates/subSilver/subSilver.cfg backups/templates/subSilver/subSilver.cfg.txt
cp processed/templates/subSilver/subSilver.cfg.txt ../../../templates/subSilver/subSilver.cfg
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
