copy viewtopic_quickreply.php ..\..\..\includes\viewtopic_quickreply.php
copy viewtopic_quickreply.tpl ..\..\..\templates\subSilver\viewtopic_quickreply.tpl
copy quickreply.gif ..\..\..\templates\subSilver\images\lang_english\quickreply.gif
copy ..\..\..\admin\admin_board.php backups\admin\admin_board.php.txt
copy processed\admin\admin_board.php.txt ..\..\..\admin\admin_board.php
copy ..\..\..\admin\admin_users.php backups\admin\admin_users.php.txt
copy processed\admin\admin_users.php.txt ..\..\..\admin\admin_users.php
copy ..\..\..\includes\functions_selects.php backups\includes\functions_selects.php.txt
copy processed\includes\functions_selects.php.txt ..\..\..\includes\functions_selects.php
copy ..\..\..\includes\usercp_avatar.php backups\includes\usercp_avatar.php.txt
copy processed\includes\usercp_avatar.php.txt ..\..\..\includes\usercp_avatar.php
copy ..\..\..\includes\usercp_register.php backups\includes\usercp_register.php.txt
copy processed\includes\usercp_register.php.txt ..\..\..\includes\usercp_register.php
copy ..\..\..\language\lang_english\lang_admin.php backups\language\lang_english\lang_admin.php.txt
copy processed\language\lang_english\lang_admin.php.txt ..\..\..\language\lang_english\lang_admin.php
copy ..\..\..\language\lang_english\lang_main.php backups\language\lang_english\lang_main.php.txt
copy processed\language\lang_english\lang_main.php.txt ..\..\..\language\lang_english\lang_main.php
copy ..\..\..\templates\subSilver\admin\board_config_body.tpl backups\templates\subSilver\admin\board_config_body.tpl.txt
copy processed\templates\subSilver\admin\board_config_body.tpl.txt ..\..\..\templates\subSilver\admin\board_config_body.tpl
copy ..\..\..\templates\subSilver\admin\user_edit_body.tpl backups\templates\subSilver\admin\user_edit_body.tpl.txt
copy processed\templates\subSilver\admin\user_edit_body.tpl.txt ..\..\..\templates\subSilver\admin\user_edit_body.tpl
copy ..\..\..\templates\subSilver\profile_add_body.tpl backups\templates\subSilver\profile_add_body.tpl.txt
copy processed\templates\subSilver\profile_add_body.tpl.txt ..\..\..\templates\subSilver\profile_add_body.tpl
copy ..\..\..\templates\subSilver\viewtopic_body.tpl backups\templates\subSilver\viewtopic_body.tpl.txt
copy processed\templates\subSilver\viewtopic_body.tpl.txt ..\..\..\templates\subSilver\viewtopic_body.tpl
copy ..\..\..\templates\subSilver\subSilver.cfg backups\templates\subSilver\subSilver.cfg.txt
copy processed\templates\subSilver\subSilver.cfg.txt ..\..\..\templates\subSilver\subSilver.cfg
copy ..\..\..\viewtopic.php backups\viewtopic.php.txt
copy processed\viewtopic.php.txt ..\..\..\viewtopic.php
